const jobs = [
    {
        id: "J001",
        title: "SDE Intern",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "Data Structures", "Algorithms"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹40k/month Internship",
        applyUrl: "https://www.flipkart.com/careers/J001",
        description: "Join the core supply chain team at Flipkart. You will work on optimizing order fulfillment systems using Java and Spring Boot. High-impact role with potential for PPO."
    },
    {
        id: "J002",
        title: "Graduate Engineer Trainee",
        company: "Infosys",
        location: "Mysore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["C#", ".NET", "SQL"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "3–5 LPA",
        applyUrl: "https://www.infosys.com/careers/J002",
        description: "Standard entry-level role following the Infosys training program. You will be trained on full-stack development and deployed to global client projects."
    },
    {
        id: "J003",
        title: "Junior Backend Developer",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Remote",
        experience: "0-1",
        skills: ["Go", "MySQL", "Redis"],
        source: "Naukri",
        postedDaysAgo: 0,
        salaryRange: "10–18 LPA",
        applyUrl: "https://razorpay.com/jobs/J003",
        description: "Work on scaling the payments gateway. Responsible for writing clean, efficient Go code and ensuring high availability of financial services."
    },
    {
        id: "J004",
        title: "Frontend Intern",
        company: "Swiggy",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["React", "CSS", "TypeScript"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "₹25k/month Internship",
        applyUrl: "https://www.swiggy.com/careers/J004",
        description: "Collaborate with the consumer-app team to build intuitive food ordering interfaces. Exposure to large-scale React applications and performance optimization."
    },
    {
        id: "J005",
        title: "React Developer",
        company: "Zomato",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React", "Redux", "Node.js"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "12–22 LPA",
        applyUrl: "https://www.zomato.com/careers/J005",
        description: "Design and implement user-facing features for Zomato's delivery platform. Focus on building reusable components and optimizing frontend performance."
    },
    {
        id: "J006",
        title: "Python Developer (Fresher)",
        company: "CRED",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Python", "Django", "PostgreSQL"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "8–12 LPA",
        applyUrl: "https://www.cred.club/careers/J006",
        description: "Backend engineering for life-style and rewards systems. You will work on high-frequency data processing and integration with credit-card networks."
    },
    {
        id: "J007",
        title: "Data Analyst Intern",
        company: "Paytm",
        location: "Noida",
        mode: "Remote",
        experience: "Fresher",
        skills: ["SQL", "Tableau", "Python"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "₹20k/month Internship",
        applyUrl: "https://paytm.com/careers/J007",
        description: "Analyze transaction data to identify patterns and fraud risks. Assist in creating dashboards for senior management decision-making."
    },
    {
        id: "J008",
        title: "QA Intern",
        company: "Freshworks",
        location: "Chennai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Selenium", "Java", "Manual Testing"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "₹15k/month Internship",
        applyUrl: "https://www.freshworks.com/careers/J008",
        description: "Support the quality assurance team in executing test cases for SaaS products. Gain hands-on experience with automation frameworks."
    },
    {
        id: "J009",
        title: "Java Developer",
        company: "TCS",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Java", "Spring MVC", "Oracle"],
        source: "LinkedIn",
        postedDaysAgo: 7,
        salaryRange: "4–7 LPA",
        applyUrl: "https://www.tcs.com/careers/J009",
        description: "Application maintenance and feature enhancement for a leading European banking client. Requires strong understanding of legacy systems and modern Java."
    },
    {
        id: "J010",
        title: "Associate Software Engineer",
        company: "Cognizant",
        location: "Pune",
        mode: "Remote",
        experience: "0-1",
        skills: ["JavaScript", "HTML/CSS", "Bootstrap"],
        source: "LinkedIn",
        postedDaysAgo: 8,
        salaryRange: "4–6 LPA",
        applyUrl: "https://www.cognizant.com/careers/J010",
        description: "Contribute to web application development for healthcare sector projects. Focus on responsive design and cross-browser compatibility."
    },
    {
        id: "J011",
        title: "Staff Engineer (Backend)",
        company: "Juspay",
        location: "Bangalore",
        mode: "Remote",
        experience: "3-5",
        skills: ["Haskell", "PureScript", "Purerl"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "30–50 LPA",
        applyUrl: "https://juspay.in/careers/J011",
        description: "Architecture and implementation of highly concurrent payment orchestration systems. Deep involvement in functional programming and distributed systems."
    },
    {
        id: "J012",
        title: "UI/UX Intern",
        company: "PhonePe",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Figma", "Adobe XD", "User Research"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹35k/month Internship",
        applyUrl: "https://www.phonepe.com/careers/J012",
        description: "Assist in designing seamless checkout experiences for millions of users. Participate in user testing and iterative design cycles."
    },
    {
        id: "J013",
        title: "Systems Engineer",
        company: "Wipro",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Linux", "Python", "BASH"],
        source: "LinkedIn",
        postedDaysAgo: 9,
        salaryRange: "4–6 LPA",
        applyUrl: "https://www.wipro.com/careers/J013",
        description: "Manage and automate server deployments for enterprise clients. Focus on reliability, security, and performance tuning."
    },
    {
        id: "J014",
        title: "Full Stack Developer",
        company: "Zoho",
        location: "Chennai",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Java", "JavaScript", "React"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "10–15 LPA",
        applyUrl: "https://www.zoho.com/careers/J014",
        description: "Build features for Zoho Books. Responsibility spans from database design to complex React components. High ownership environment."
    },
    {
        id: "J015",
        title: "Cloud Consultant",
        company: "IBM",
        location: "Hyderabad",
        mode: "Remote",
        experience: "0-1",
        skills: ["AWS", "Terraform", "CloudFormation"],
        source: "Indeed",
        postedDaysAgo: 10,
        salaryRange: "6–10 LPA",
        applyUrl: "https://www.ibm.com/careers/J015",
        description: "Guide clients through cloud migration strategy and implementation. Focus on building scalable, secure cloud-native architectures."
    },
    {
        id: "J016",
        title: "Software Engineer",
        company: "SAP",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["ABAP", "Java", "HANA"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "14–22 LPA",
        applyUrl: "https://www.sap.com/careers/J016",
        description: "Develop enterprise software solutions within the SAP ecosystem. Enhance core modules for finance and HR management."
    },
    {
        id: "J017",
        title: "Data Scientist",
        company: "Ola",
        location: "Bangalore",
        mode: "Onsite",
        experience: "3-5",
        skills: ["Python", "Spark", "Machine Learning"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "20–35 LPA",
        applyUrl: "https://www.olacabs.com/careers/J017",
        description: "Develop algorithms for ride pricing and demand forecasting. Work with massive datasets to improve fleet efficiency and user experience."
    },
    {
        id: "J018",
        title: "Security Analyst",
        company: "Jio",
        location: "Mumbai",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Cybersecurity", "SIEM", "Splunk"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "8–14 LPA",
        applyUrl: "https://www.jio.com/careers/J018",
        description: "Monitor network traffic for security threats and breaches. Participate in incident response and vulnerability assessments."
    },
    {
        id: "J019",
        title: "iOS Developer",
        company: "BharatPe",
        location: "Delhi",
        mode: "Remote",
        experience: "1-3",
        skills: ["Swift", "SwiftUI", "Combine"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "15–25 LPA",
        applyUrl: "https://www.bharatpe.com/careers/J019",
        description: "Lead the development of merchant-facing iOS applications. High focus on UI precision and offline-first functionalities."
    },
    {
        id: "J020",
        title: "Android Developer",
        company: "Meesho",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Kotlin", "Jetpack Compose", "Dagger"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "15–28 LPA",
        applyUrl: "https://www.meesho.io/careers/J020",
        description: "Build robust Android applications for a diverse user base. Focus on low-end device optimization and smooth user journeys."
    },
    {
        id: "J021",
        title: "Java Developer (0-1)",
        company: "Dell",
        location: "Bangalore",
        mode: "Remote",
        experience: "0-1",
        skills: ["Java", "Spring Boot", "Elasticsearch"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "8–12 LPA",
        applyUrl: "https://jobs.dell.com/J021",
        description: "Develop and maintain internal business applications. Integrate complex APIs and manage distributed service architectures."
    },
    {
        id: "J022",
        title: "DevOps Engineer",
        company: "Groww",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Docker", "Kubernetes", "Jenkins"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "12–20 LPA",
        applyUrl: "https://groww.in/careers/J022",
        description: "Streamline CI/CD pipelines and manage production infrastructure. Focus on scalability and observability of financial trading systems."
    },
    {
        id: "J023",
        title: "Data Engineer",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Kafka", "Airflow", "Python"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "18–28 LPA",
        applyUrl: "https://www.flipkart.com/careers/J023",
        description: "Build reliable data pipelines for analytics and machine learning. Experience with high-throughput messaging systems is essential."
    },
    {
        id: "J024",
        title: "Blockchain Engineer",
        company: "Polygon",
        location: "Remote",
        experience: "1-3",
        skills: ["Solidity", "Rust", "Ethereum"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "30–60 LPA",
        applyUrl: "https://polygon.technology/careers/J024",
        description: "Design and implement secure smart contracts for decentralized finance protocols. Deep understanding of web3 security is required."
    },
    {
        id: "J025",
        title: "Machine Learning Intern",
        company: "Amazon",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["NLP", "PyTorch", "Python"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "₹50k/month Internship",
        applyUrl: "https://www.amazon.jobs/J025",
        description: "Work with the Alexa team on natural language understanding. Assist in training and evaluating deep learning models."
    },
    {
        id: "J026",
        title: "QA Automation Engineer",
        company: "Oracle",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "3-5",
        skills: ["Cypress", "JavaScript", "SQL"],
        source: " LinkedIn",
        postedDaysAgo: 7,
        salaryRange: "16–28 LPA",
        applyUrl: "https://oracle.com/careers/J026",
        description: "Lead end-to-end testing for enterprise database tools. Develop and maintain automated test suites for cloud services."
    },
    {
        id: "J027",
        title: "Software Engineer II",
        company: "Microsoft",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Azure", "TypeScript", "React"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "25–45 LPA",
        applyUrl: "https://careers.microsoft.com/J027",
        description: "Contribute to the development of Azure Portal services. Focus on building high-performance, accessible web interfaces."
    },
    {
        id: "J028",
        title: "Backend Intern",
        company: "Postman",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Node.js", "Redis", "Kafka"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "₹45k/month Internship",
        applyUrl: "https://www.postman.com/careers/J028",
        description: "Join the core platform team. Help build and scale internal microservices that power the Postman collaborative environment."
    },
    {
        id: "J029",
        title: "Associate Product Manager",
        company: "Paytm",
        location: "Noida",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Product Roadmap", "Analytics", "Communication"],
        source: "LinkedIn",
        postedDaysAgo: 6,
        salaryRange: "10–15 LPA",
        applyUrl: "https://paytm.com/careers/J029",
        description: "Shape the future of digital payments. Work with design and engineering teams to deliver features based on user feedback."
    },
    {
        id: "J030",
        title: "Site Reliability Engineer",
        company: "Urban Company",
        location: "Gurgaon",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Prometheus", "Grafana", "Ansible"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "14–24 LPA",
        applyUrl: "https://www.urbancompany.com/careers/J030",
        description: "Ensure the reliability and performance of services across multiple markets. Automate incident management and toil reduction."
    },
    {
        id: "J031",
        title: "Junior Java Developer",
        company: "Accenture",
        location: "Chennai",
        mode: "Remote",
        experience: "0-1",
        skills: ["Java", "Spring", "Microservices"],
        source: "LinkedIn",
        postedDaysAgo: 8,
        salaryRange: "4–6 LPA",
        applyUrl: "https://www.accenture.com/careers/J031",
        description: "Develop backend services for enterprise automation projects. Work in an agile environment with focus on clean code and documentation."
    },
    {
        id: "J032",
        title: "React Native Developer",
        company: "Licious",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React Native", "JavaScript", "Push Notifications"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "12–20 LPA",
        applyUrl: "https://www.licious.in/careers/J032",
        description: "Build cross-platform mobile applications for consumer delivery. Focus on high-fidelity animations and performance."
    },
    {
        id: "J033",
        title: "Security Engineer",
        company: "InMobi",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["Pentesting", "Burp Suite", "AWS Security"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "20–35 LPA",
        applyUrl: "https://www.inmobi.com/careers/J033",
        description: "Perform regular security audits and penetration tests on ad-tech platform infrastructure. Design secure development lifecycles."
    },
    {
        id: "J034",
        title: "Documentation Intern",
        company: "Postman",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Technical Writing", "API Documentation", "Markdown"],
        source: "LinkedIn",
        postedDaysAgo: 9,
        salaryRange: "₹30k/month Internship",
        applyUrl: "https://www.postman.com/careers/J034",
        description: "Help create clear and concise documentation for Postman APIs. Work closely with product and engineering teams."
    },
    {
        id: "J035",
        title: "Associate Data Scientist",
        company: "Droom",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Python", "Pandas", "Linear Regression"],
        source: "Indeed",
        postedDaysAgo: 7,
        salaryRange: "6–9 LPA",
        applyUrl: "https://droom.in/careers/J035",
        description: "Use statistical models to improve car valuation engines. Responsible for data cleaning and exploratory data analysis."
    },
    {
        id: "J036",
        title: "QA Lead",
        company: "Capgemini",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["Test Strategy", "Appium", "Agile"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "12–20 LPA",
        applyUrl: "https://www.capgemini.com/careers/J036",
        description: "Define testing strategies for large-scale enterprise migrations. Manage a team of junior and senior QA engineers."
    },
    {
        id: "J037",
        title: "Cloud Architect",
        company: "VelloreIT",
        location: "Chennai",
        mode: "Onsite",
        experience: "3-5",
        skills: ["GCP", "Kubernetes", "IAM"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "25–40 LPA",
        applyUrl: "https://www.velloreit.com/careers/J037",
        description: "Design cloud-native infrastructures for global manufacturing clients. Lead cloud transformation journeys using GCP services."
    },
    {
        id: "J038",
        title: "Full Stack Intern",
        company: "NextGen Labs",
        location: "Pune",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Next.js", "Firebase", "Tailwind"],
        source: "Indeed",
        postedDaysAgo: 2,
        salaryRange: "₹18k/month Internship",
        applyUrl: "https://nextgenlabs.ai/careers/J038",
        description: "Build MVPs for innovative startup ideas. Opportunity to work on bleeding-edge technologies and modern web frameworks."
    },
    {
        id: "J039",
        title: "Software Engineer",
        company: "Citrix",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["C++", "Networking", "Virtualization"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "18–28 LPA",
        applyUrl: "https://jobs.citrix.com/J039",
        description: "Work on core virtualization technologies. Debug and optimize network stack for low-latency desktop delivering protocols."
    },
    {
        id: "J040",
        title: "Mobile Dev Intern",
        company: "Pepperfry",
        location: "Mumbai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Flutter", "Dart", "UX Basics"],
        source: "Indeed",
        postedDaysAgo: 6,
        salaryRange: "₹22k/month Internship",
        applyUrl: "https://www.pepperfry.com/careers/J040",
        description: "Support the mobile team in building features for furniture shopping experience. Exposure to Flutter state management."
    },
    {
        id: "J041",
        title: "Backend Dev (Java)",
        company: "Standard Chartered",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["Java 17", "Spring Boot", "Kafka"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "14–24 LPA",
        applyUrl: "https://www.sc.com/careers/J041",
        description: "Modernizing banking backend services with high-availability microservices. Deep involvement in event-driven architecture."
    },
    {
        id: "J042",
        title: "Staff Frontend Engineer",
        company: "PharmEasy",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["React", "Next.js", "Web Performance"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "30–50 LPA",
        applyUrl: "https://pharmeasy.in/careers/J042",
        description: "Architecture leader for pharmacy e-commerce frontend. Ownership of CI/CD pipelines, SSR strategies, and core UI components."
    },
    {
        id: "J043",
        title: "Junior Data Analyst",
        company: "Mu Sigma",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["R", "SQL", "Excel"],
        source: "LinkedIn",
        postedDaysAgo: 9,
        salaryRange: "4–6 LPA",
        applyUrl: "https://www.mu-sigma.com/careers/J043",
        description: "Perform data driven decision making for Fortune 500 clients. Translate complex business questions into actionable statistical models."
    },
    {
        id: "J044",
        title: "Product Intern",
        company: "InShorts",
        location: "Noida",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Market Research", "Product Design", "Agile"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "₹15k/month Internship",
        applyUrl: "https://www.inshorts.com/careers/J044",
        description: "Support product managers in research and wireframing for new content products. Exposure to rapid iteration cycles."
    },
    {
        id: "J045",
        title: "Staff Research Engineer",
        company: "TCS Research",
        location: "Pune",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["Deep Learning", "Graph Neural Networks", "Python"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "20–35 LPA",
        applyUrl: "https://www.tcs.com/research/J045",
        description: "Lead research projects in the intersection of AI and manufacturing. Publish papers in top conferences and translate research into patents."
    },
    {
        id: "J046",
        title: "Android Dev Intern",
        company: "Upstox",
        location: "Mumbai",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Kotlin", "MVVM", "Retrofit"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹40k/month Internship",
        applyUrl: "https://upstox.com/careers/J046",
        description: "Work on the award-winning trading app. Gain hands-on experience in building high-frequency stock update interfaces on Android."
    },
    {
        id: "J047",
        title: "Node.js Developer",
        company: "Yellow.ai",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["Node.js", "Express", "MongoDB"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "12–20 LPA",
        applyUrl: "https://yellow.ai/careers/J047",
        description: "Build scalable APIs for conversational AI platforms. Work on real-time messaging systems and complex chatbot workflows."
    },
    {
        id: "J048",
        title: "SDE I (Frontend)",
        company: "Dunzo",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["React", "Javascript", "SASS"],
        source: "Indeed",
        postedDaysAgo: 4,
        salaryRange: "10–18 LPA",
        applyUrl: "https://www.dunzo.com/careers/J048",
        description: "Improve the consumer checkout flow. Focus on building performant web experiences for local delivery services."
    },
    {
        id: "J049",
        title: "Lead Backend Developer",
        company: "Cloudnine",
        location: "Cloud City",
        mode: "Remote",
        experience: "3-5",
        skills: ["Node.js", "AWS Lambdas", "DynamoDB"],
        source: "Indeed",
        postedDaysAgo: 2,
        salaryRange: "22–35 LPA",
        applyUrl: "https://www.cloudnine.sh/careers/J049",
        description: "Architect and lead the backend team for a serverless native healthcare platform. Deep focus on data privacy and scalable systems."
    },
    {
        id: "J050",
        title: "Quality Engineer",
        company: "Adobe",
        location: "Noida",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Java", "Automation Testing", "Jenkins"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "18–28 LPA",
        applyUrl: "https://www.adobe.com/careers/J050",
        description: "Ensure the world-class quality of creative cloud applications. Focus on performance testing and cross-platform automation."
    },
    {
        id: "J051",
        title: "Product Designer",
        company: "Unacademy",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["UI Principles", "Animation", "Prototyping"],
        source: "LinkedIn",
        postedDaysAgo: 6,
        salaryRange: "15–25 LPA",
        applyUrl: "https://unacademy.com/careers/J051",
        description: "Design learning experiences for millions of students. Work at the intersection of psychology, education, and modern design."
    },
    {
        id: "J052",
        title: "Junior Site Reliability Eng",
        company: "Gojek",
        location: "Bangalore",
        mode: "Remote",
        experience: "0-1",
        skills: ["Go", "BASH", "Container Orchestration"],
        source: "Indeed",
        postedDaysAgo: 7,
        salaryRange: "12–18 LPA",
        applyUrl: "https://www.gojek.io/careers/J052",
        description: "Manage and monitor the infrastructure of a super-app. High responsibility role involving production support and automation."
    },
    {
        id: "J053",
        title: "Ruby on Rails Intern",
        company: "BigBasket",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Ruby", "RoR", "SQL"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "₹28k/month Internship",
        applyUrl: "https://www.bigbasket.com/careers/J053",
        description: "Contribute to the legacy RoR monolith. Assist in migrating core features to modern microservices."
    },
    {
        id: "J054",
        title: "Embedded Eng Intern",
        company: "Ather Energy",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["C", "RTOS", "Microcontrollers"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹25k/month Internship",
        applyUrl: "https://www.atherenergy.com/careers/J054",
        description: "Support the battery management system team. Participate in firmware testing and hardware-software integration."
    },
    {
        id: "J055",
        title: "Associate Dev (Python)",
        company: "Capgemini",
        location: "Bangalore",
        mode: "Remote",
        experience: "0-1",
        skills: ["Python", "Flask", "PostgreSQL"],
        source: "Naukri",
        postedDaysAgo: 10,
        salaryRange: "4–6 LPA",
        applyUrl: "https://www.capgemini.com/careers/J055",
        description: "Build robust backend solutions for client automation projects. Collaborate with global teams on feature additions and bug fixes."
    },
    {
        id: "J056",
        title: "Software Engineer III",
        company: "Twilio",
        location: "Bangalore",
        mode: "Remote",
        experience: "3-5",
        skills: ["Java", "Distributed Systems", "Cloud Security"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "35–55 LPA",
        applyUrl: "https://www.twilio.com/careers/J056",
        description: "Senior individual contributor role for core communication platform. Focus on reliability, high scale architecture, and low-latency API design."
    },
    {
        id: "J057",
        title: "Data Analyst",
        company: "Fractal Analytics",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Python", "PowerBI", "Stats"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "10–16 LPA",
        applyUrl: "https://fractal.ai/careers/J057",
        description: "Convert unstructured data into business insights for global CPG firms. Lead client presentations and technical strategy."
    },
    {
        id: "J058",
        title: "Staff SRE",
        company: "Hike",
        location: "Remote",
        experience: "3-5",
        skills: ["Kubernetes", "Observability", "Terraform"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "25–45 LPA",
        applyUrl: "https://hike.in/careers/J058",
        description: "Build and scale the infrastructure for our social gaming universe. Ownership of stability, cost optimization, and CI/CD platforms."
    },
    {
        id: "J059",
        title: "Junior Security Eng",
        company: "Cisco",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["TCP/IP", "Wireshark", "Firewalls"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "8–12 LPA",
        applyUrl: "https://jobs.cisco.com/J059",
        description: "Configure and troubleshoot security devices for internal enterprise networks. Respond to alerts and handle software patches."
    },
    {
        id: "J060",
        title: "Staff Product Manager",
        company: "Unacademy",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["Strategy", "A/B Testing", "Growth"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "35–60 LPA",
        applyUrl: "https://unacademy.com/careers/J060",
        description: "Lead the growth and monetization product charter. High ownership role responsible for major business metrics and KPIs."
    }
];
